### ISSUE TITLE
Zeitwerk load issue with Rails (via openapi_first)

### ISSUE THREAD

**Issue by twe4ked** [ahx/openapi_parameters#1]
Hey! I like how this gem has been split out. Version 1 of openapi_first looks fantastic!

When the `eager_load` config is enabled:

```ruby
Rails.application.configure do
  config.eager_load = true
end
```

I'm seeing the following error coming from Zeitwerk. I assume it's seeing the `lib/openapi_parameters/errors.rb` file and assuming there will be an `Errors` name.

```
$ bin/rails zeitwerk:check
Hold on, I am eager loading the application.
rails aborted!
NameError: uninitialized constant OpenapiParameters::Errors
```

I haven't played around with the Zeitwerk `for_gem` functionality at all so I'm not sure how it's meant to interact with Rails.

For now I've defined the class myself in an initializer.

Versions:

```
openapi_first (1.0.0.beta3)
  hanami-router (~> 2.0.0)
  json_refs (~> 0.1, >= 0.1.7)
  json_schemer (~> 0.2.16)
  multi_json (~> 1.14)
  openapi_parameters (~> 0.2)
  rack (>= 2.2, < 4.0)
openapi_parameters (0.2.2)
  rack (>= 2.2)
  zeitwerk (~> 2.6)
```

Happy to implement a fix for this, not sure what you'd like to do though. Cheers!

**Comment by jan-bw** [comment]
Hi, I run into the same issue and it's mitigated by encapsulating errors in a `module Errors`. Here is the diff: https://github.com/ahx/openapi_parameters/compare/0.2.2...MrBananaLord:openapi_parameters:fix-zeitwerk 
can't open a PR as I am not a collaborator :)

**Comment by MrBananaLord** [comment]
Hi, I run into the same issue and it's mitigated by encapsulating errors in a module Errors. Here is the diff: https://github.com/ahx/openapi_parameters/compare/0.2.2...MrBananaLord:openapi_parameters:fix-zeitwerk
can't open a PR as I am not a collaborator :)

**Comment by ahx** [comment]
Closed via https://github.com/ahx/openapi_parameters/pull/4

Sorry for the late reply. This got lot in github notifications. Fix will be released in 0.3.1 today.

**Comment by twe4ked** [comment]
Thanks! 🙏

**Comment by ahx** [comment]
For whom it might concern: I will release a new version of openapi_first this weekend. Probably another beta.
